services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: three60_fastapi:v1.0
    container_name: three60_fastapi
    restart: always  # Ensures the container restarts if it crashes or the system reboots
    ports:
      - "8778:8000"
    volumes:
      - ./static:/app/static
      - ./temp:/app/temp
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db:5432/three60}
      - SECRET_KEY=${SECRET_KEY:-your_secret_key_here}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS:-["http://localhost:3000","http://localhost:8000"]}
    networks:
      - three60_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/docs" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  three60_network:
    driver: bridge